version: '3.7'
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: chnk_discord_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432